#!/usr/bin/env bash

if [ $# -gt 0 ]; then
  CMD=$1
  PORT=5554
  echo "Starting emulator[$PORT]..."
  emulator64-x86 -avd test -noaudio -no-window -gpu off -verbose -qemu -usbdevice tablet & >> emulator.log
  wait-for-emulator
  $CMD
else
  echo "No command is specified"
fi
